queue:
  brokerUrl: tcp://localhost:61616
  connectID: connectId
  username: username
  password: password

  monitor:
    browseQueues: Q1,Q2,Q3
    timeInterval : 10000

  roundTrip:
    times : 100

  requestReplier:
    defaultQueue : Q1
    defaultMode : LOWERCASE
    requestContent : Good good work, day day UP.
    requestInterval : 2000

  transactionTalker:
    sendQueue : SEND
    receiveQueue : RECEIVE
