### active Mq configuration
spring:
  activemq:
    brokerUrl: tcp://127.0.0.1:55555
    inMemory: true
    user: default
    password: default
    pool:
      enabled: false

### client configuration
activeMq:
  jms:
    demoQueueName: defaultMq